### ISSUE TITLE
安装完依赖后，跑不起来，一直在转圈

### ISSUE THREAD

**Issue by cmdparkour** [yuzai/base-editor#1]
![image](https://user-images.githubusercontent.com/35911743/165699681-b9152484-d065-4c68-8300-567fcdec2168.png)

**Comment by yuzai** [comment]
能打到网络下，看看是什么资源没有加载下来吗？

**Comment by yuzai** [comment]
里面依赖的资源比较多，一个是github仓库部署的静态资源，还有编辑器本身依赖的monaco-editor的cdn资源：https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.30.1/min/vs/loader.min.js
